name: Pipeline

on:
  push:
    branches:
      - master

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Checkout
        uses: actions/checkout@v2
      - name: Linting
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.31
      - name: Unit Testing
        run: go test -tags=unit ./...
      - name: Integration Testing
        run: go test -tags=integration ./...
